import {sqliteTable,text,integer,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const people=sqliteTable('people',{id:text('id').primaryKey(),name:text('name').notNull(),city:text('city').notNull(),profile:text('profile').notNull().default('{}')});
export const documents=sqliteTable('documents',{id:text('id').primaryKey(),person:text('person').notNull().references(()=>people.id),category:text('category').notNull(),name:text('name').notNull(),size:integer('size').notNull(),created:text('created').notNull()},t=>[index('idx_documents_person').on(t.person)]);
// 回覧板：職員への周知。既読は職員名簿の各職員が「見ました」を押した記録。退職・掲載終了はフラグ、削除は管理者のみ。
export const boardStaff=sqliteTable('board_staff',{id:text('id').primaryKey(),name:text('name').notNull(),active:integer('active').notNull().default(1),admin:integer('admin').notNull().default(0),created:text('created').notNull()});
// binder=1 のフォルダーは「シフト集」のように一覧で1枚の綴りにまとめる
export const boardFolders=sqliteTable('board_folders',{id:text('id').primaryKey(),name:text('name').notNull(),color:text('color').notNull(),binder:integer('binder').notNull().default(0),created:text('created').notNull()});
// version は最新の版、thumb は一覧プレビューを作った版（0は無し）。due=確認期限、expires=掲載期限（nullは無期限）
export const boardPosts=sqliteTable('board_posts',{id:text('id').primaryKey(),folder:text('folder').references(()=>boardFolders.id),title:text('title').notNull(),body:text('body').notNull().default(''),author:text('author').notNull(),important:integer('important').notNull().default(0),archived:integer('archived').notNull().default(0),created:text('created').notNull(),target:text('target').notNull().default(''),due:text('due'),expires:text('expires'),pinned:integer('pinned').notNull().default(0),version:integer('version').notNull().default(1),thumb:integer('thumb').notNull().default(0)},t=>[index('idx_board_posts_folder').on(t.folder)]);
export const boardVersions=sqliteTable('board_versions',{id:text('id').primaryKey(),post:text('post').notNull().references(()=>boardPosts.id),version:integer('version').notNull(),note:text('note').notNull().default(''),author:text('author').notNull(),created:text('created').notNull()},t=>[index('idx_board_versions_post').on(t.post)]);
export const boardFiles=sqliteTable('board_files',{id:text('id').primaryKey(),post:text('post').notNull().references(()=>boardPosts.id),name:text('name').notNull(),size:integer('size').notNull(),created:text('created').notNull(),version:integer('version').notNull().default(1)},t=>[index('idx_board_files_post').on(t.post)]);
// version はその職員が確認した版。最新の版より小さければ「未確認」
export const boardReads=sqliteTable('board_reads',{post:text('post').notNull().references(()=>boardPosts.id),staff:text('staff').notNull().references(()=>boardStaff.id),readAt:text('read_at').notNull(),version:integer('version').notNull().default(1)},t=>[primaryKey({columns:[t.post,t.staff]})]);
export const boardComments=sqliteTable('board_comments',{id:text('id').primaryKey(),post:text('post').notNull().references(()=>boardPosts.id),staff:text('staff').references(()=>boardStaff.id),name:text('name').notNull(),body:text('body').notNull(),created:text('created').notNull()},t=>[index('idx_board_comments_post').on(t.post)]);
export const boardTemplates=sqliteTable('board_templates',{id:text('id').primaryKey(),name:text('name').notNull(),title:text('title').notNull(),body:text('body').notNull().default(''),target:text('target').notNull().default(''),folder:text('folder'),created:text('created').notNull()});
// 管理者の暗証番号（ハッシュ）など
export const boardSettings=sqliteTable('board_settings',{key:text('key').primaryKey(),value:text('value').notNull()});
// 日々の記録作成：その人の特徴、文例（ノウビーの書き方の見本）、作成した記録、AIの設定
export const personTraits=sqliteTable('person_traits',{person:text('person').primaryKey().references(()=>people.id),traits:text('traits').notNull().default(''),updated:text('updated').notNull()});
export const recordExamples=sqliteTable('record_examples',{id:text('id').primaryKey(),kind:text('kind').notNull(),body:text('body').notNull(),created:text('created').notNull()});
export const dailyRecords=sqliteTable('daily_records',{id:text('id').primaryKey(),person:text('person').notNull().references(()=>people.id),date:text('date').notNull(),memo:text('memo').notNull().default(''),record:text('record').notNull().default(''),consideration:text('consideration').notNull().default(''),author:text('author').notNull().default(''),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('idx_daily_records_person').on(t.person,t.date)]);
// AIの接続先など（鍵はサーバーの中だけで使い、画面には返さない）
export const appSettings=sqliteTable('app_settings',{key:text('key').primaryKey(),value:text('value').notNull()});
