'use client';
import {useEffect,useRef,useState,type FormEvent,type CSSProperties} from 'react';
import {X,ChevronLeft,MessageCircle,FolderPlus,UserPlus,Layers,KeyRound,ShieldCheck,Trash2} from 'lucide-react';
import {folderColors,suggestedFolders,boardLimits,needsMyCheck,type Board,type Staff,type Folder,type PostSummary,type PostDetail,type Template} from '../lib/board';
import {makeThumbnail} from '../lib/thumbnail';
import {PostList,type ListFilter} from './board/PostList';
import {PostView} from './board/PostView';
import {WriteForm,VersionForm,emptyDraft,type Draft} from './board/WriteForm';
import {tagStyle} from './board/parts';
type Step='who'|'menu'|'list'|'post'|'write'|'version'|'folders'|'folderEdit'|'staff'|'pin'|'pinSetup'|'confirmDelete';
type Line={speaker:'student'|'you';text:string};
type ApiError=Error&{status?:number};
export const boardStaffKey='board-staff-id';
const allFilter:ListFilter={folder:'all',unread:false,important:false,due:false,archived:false,query:''};
export default function BoardConversation({origin,onClose}:{origin:{x:number;y:number};onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),feed=useRef<HTMLDivElement>(null),returnFocus=useRef<Element|null>(null);
 const [step,setStep]=useState<Step>('menu'),[lines,setLines]=useState<Line[]>([{speaker:'student',text:'こんにちは。回覧板の係です。'}]);
 const [board,setBoard]=useState<Board>({staff:[],folders:[],posts:[],templates:[],hasPin:false}),[me,setMe]=useState(''),[detail,setDetail]=useState<PostDetail|null>(null);
 const [filter,setFilter]=useState<ListFilter>(allFilter),[draft,setDraft]=useState<Draft>(emptyDraft());
 const [folderDraft,setFolderDraft]=useState({id:'',name:'',color:'green',binder:false}),[staffName,setStaffName]=useState('');
 const [pinInput,setPinInput]=useState(''),[pinSetup,setPinSetup]=useState({current:'',next:'',again:''});
 const adminPin=useRef(''),pendingAdmin=useRef<((pin:string)=>Promise<void>)|null>(null);
 const [busy,setBusy]=useState(true),[error,setError]=useState('');
 const myself=board.staff.find(s=>s.id===me),myName=myself?.name??'',isAdmin=!!myself?.admin;
 const activeStaff=board.staff.filter(s=>s.active);
 const unreadOf=(b:Board,id:string)=>b.posts.filter(p=>needsMyCheck(p,id,b.staff)).length;
 const unread=unreadOf(board,me);
 useEffect(()=>{returnFocus.current=document.activeElement;dialog.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;(returnFocus.current as HTMLElement)?.focus?.()}},[]);
 useEffect(()=>{if(step==='post'){feed.current?.querySelector('.boardPost')?.scrollIntoView({block:'start'});return}feed.current?.scrollTo({top:feed.current.scrollHeight,behavior:'instant'})},[lines,step,error]);
 // eslint-disable-next-line react-hooks/exhaustive-deps -- 開いたときに一度だけ読み込む
 useEffect(()=>{let saved='';try{saved=localStorage.getItem(boardStaffKey)||''}catch{}void (async()=>{try{const data=await load(saved);const who=data.staff.find(s=>s.active&&s.id===saved);if(who){setMe(saved);const n=unreadOf(data,saved);setLines([{speaker:'student',text:'こんにちは、'+who.name+'さん。回覧板の係です。'+(n?'まだ確認していないお知らせが '+n+' 件あります。':'新しいお知らせはすべて確認済みです。')}])}else{setLines([{speaker:'student',text:data.staff.length?'こんにちは。回覧板の係です。まず、あなたのお名前を選んでください。「見ました」の記録に使います。':'こんにちは。回覧板の係です。はじめに、職員のお名前を登録しましょう。「見ました」の記録に使います。'}]);setStep('who')}}catch(e){setError((e as Error).message)}finally{setBusy(false)}})()},[]);
 // eslint-disable-next-line @typescript-eslint/no-explicit-any -- 呼び出し側で型を付ける（StudentConversationと同じ）
 async function api(url:string,init?:RequestInit):Promise<any>{const r=await fetch(url,init);const data=await r.json() as {error?:string};if(!r.ok){const e:ApiError=Error(data.error||'処理できませんでした。もう一度お試しください。');e.status=r.status;throw e}return data;}
 const send=(method:string,body:object)=>api('/api/board',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 const patch=(body:object)=>send('PATCH',body);
 async function load(staff=me){const data:Board=await api('/api/board?staff='+encodeURIComponent(staff));setBoard(data);return data;}
 function say(user:string,reply:string,next:Step){setError('');setLines(prev=>[...prev,{speaker:'you',text:user},{speaker:'student',text:reply}]);setStep(next)}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function home(){if(!me){setStep('who');return}setError('');setStep('menu');setLines([{speaker:'student',text:'ほかに、お手伝いできることはありますか？'+(unread?'（未確認 '+unread+' 件）':'')}])}
 // 管理者だけの操作：暗証番号を一度入れれば、この会話の間は覚えておく
 function withAdmin(user:string,work:(pin:string)=>Promise<void>){
  if(!isAdmin){setError(board.hasPin?'この操作は管理者だけができます。職員名簿で管理者になっている人が操作してください。':'まだ管理者がいません。「職員名簿・管理者」から管理者の暗証番号を決めてください。');return}
  const ask=()=>{pendingAdmin.current=work;setPinInput('');say(user,'管理者の操作です。暗証番号を入れてください。','pin')};
  if(!adminPin.current){ask();return}
  void run(async()=>{try{await work(adminPin.current)}catch(e){if((e as ApiError).status===403){adminPin.current='';ask();return}throw e}});
 }
 function submitPin(e:FormEvent){e.preventDefault();const work=pendingAdmin.current;if(!work)return;void run(async()=>{await work(pinInput);adminPin.current=pinInput;pendingAdmin.current=null;setPinInput('')})}
 function chooseMe(s:Staff){setMe(s.id);adminPin.current='';try{localStorage.setItem(boardStaffKey,s.id)}catch{}void run(async()=>{const data=await load(s.id);const n=unreadOf(data,s.id);say(s.name+' です',s.name+'さんですね。'+(n?'まだ確認していないお知らせが '+n+' 件あります。':'新しいお知らせはありません。')+'何をしましょうか？','menu')})}
 function addStaff(e:FormEvent,thenChoose:boolean){e.preventDefault();const name=staffName.trim();if(!name)return;void run(async()=>{const s:Staff=await patch({action:'staff',name});setStaffName('');await load();if(thenChoose)chooseMe(s);else say(name+' さんを登録','名簿に '+name+' さんを登録しました。','staff')})}
 function setActive(s:Staff,active:boolean){void run(async()=>{await patch({action:'staff',id:s.id,active});await load();say(s.name+(active?' さんを名簿に戻す':' さんを退職・休職にする'),active?s.name+' さんを名簿に戻しました。':s.name+' さんを「まだの人」から外しました。これまでの「見ました」の記録は残っています。','staff')})}
 function setStaffAdmin(s:Staff,admin:boolean){withAdmin(s.name+(admin?' さんを管理者にする':' さんを管理者から外す'),async pin=>{await patch({action:'admin',staff:me,pin,target:s.id,admin});await load();say(s.name+(admin?' さんを管理者にする':' さんを管理者から外す'),admin?s.name+' さんを管理者にしました。暗証番号は口頭などで伝えてください。':s.name+' さんを管理者から外しました。','staff')})}
 function savePin(e:FormEvent){e.preventDefault();if(pinSetup.next!==pinSetup.again){setError('確認用の暗証番号が一致しません。');return}void run(async()=>{await patch({action:'setPin',staff:me,pin:pinSetup.current,newPin:pinSetup.next});adminPin.current=pinSetup.next;setPinSetup({current:'',next:'',again:''});await load();say('暗証番号を決める',board.hasPin?'管理者の暗証番号を変えました。':'暗証番号を決めました。'+myName+'さんが最初の管理者です。削除などの管理者の操作で使います。','staff')})}
 function openList(label:string,unreadOnly=false){setFilter({...allFilter,unread:unreadOnly});void run(async()=>{const data=await load();say(label,data.posts.length?'お知らせの一覧です。フォルダーや検索で探せます。':'まだお知らせはありません。最初のお知らせを回してみましょう。','list')})}
 function openPost(p:PostSummary){void run(async()=>{const d:PostDetail=await api('/api/board?post='+p.id);setDetail(d);const mine=d.reads.find(r=>r.staff===me);say(p.title,mine&&mine.version>=d.post.version?'こちらのお知らせです。確認済みです。':mine?'新しい版が追加されたお知らせです。見たら「見ました」を押してください。':'こちらのお知らせです。読んだら「見ました」を押してください。','post')})}
 async function refreshPost(id:string){const [d]=await Promise.all([api('/api/board?post='+id),load()]);setDetail(d);}
 function postAction(user:string,reply:string,body:object){const id=detail!.post.id;void run(async()=>{await patch({...body,id});await refreshPost(id);say(user,reply,'post')})}
 async function withThumb(form:FormData,files:File[]){const thumb=await makeThumbnail(files);if(thumb)form.set('thumb',new File([thumb],'thumb.'+(thumb.type==='image/webp'?'webp':'jpg'),{type:thumb.type}));return form}
 function startWrite(){setDraft(emptyDraft(filter.folder!=='all'&&filter.folder!=='none'?filter.folder:''));say('お知らせを回したい','件名と内容を書いてください。テンプレートからも書けます。シフト表などのPDFも付けられます。','write')}
 function submitPost(form:FormData,files:File[]){form.set('author',me);void run(async()=>{const {id}=await api('/api/board',{method:'POST',body:await withThumb(form,files)});await refreshPost(id);say(draft.title.trim(),'回覧板に載せました。だれが見たかは、この画面でいつでも確認できます。','post')})}
 function submitVersion(form:FormData,files:File[]){const id=detail!.post.id;form.set('author',me);form.set('post',id);void run(async()=>{const {version}=await api('/api/board',{method:'POST',body:await withThumb(form,files)});await refreshPost(id);say('新しい版を追加','第'+version+'版を追加しました。前の版も「これまでの版」から見られます。みなさんにもう一度「見ました」をお願いしています。','post')})}
 function saveTemplate(name:string){void run(async()=>{await patch({action:'template',name,title:draft.title,body:draft.body,target:draft.target,folder:draft.folder});await load();setLines(prev=>[...prev,{speaker:'student',text:'テンプレート「'+name+'」を保存しました。次からワンタップで使えます。'}])})}
 function deleteTemplate(t:Template){withAdmin('テンプレート「'+t.name+'」を削除',async pin=>{await send('DELETE',{kind:'template',id:t.id,staff:me,pin});await load();say('テンプレート「'+t.name+'」を削除','テンプレートを削除しました。','write')})}
 function deleteComment(id:string){const post=detail!.post.id;withAdmin('コメントを削除',async pin=>{await send('DELETE',{kind:'comment',id,staff:me,pin});await refreshPost(post);say('コメントを削除','コメントを削除しました。','post')})}
 function deletePost(){const p=detail!.post;withAdmin('「'+p.title+'」を削除する',async pin=>{await send('DELETE',{kind:'post',id:p.id,staff:me,pin});setDetail(null);await load();say('「'+p.title+'」を削除する','削除しました。添付ファイル・確認記録・コメントも消えました。','list')})}
 function saveFolder(e:FormEvent){e.preventDefault();void run(async()=>{const f:Folder=await patch({action:'folder',...folderDraft,name:folderDraft.name.trim()});await load();say(f.name,(folderDraft.id?'「'+f.name+'」を変更しました。':'「'+f.name+'」フォルダーを作りました。')+(f.binder?'一覧では1つの綴りにまとまります。':''),'folders')})}
 function quickFolder(name:string,color:string,binder:boolean){void run(async()=>{await patch({action:'folder',name,color,binder});await load();say(name+' フォルダーを作る','「'+name+'」フォルダーを作りました。'+(binder?'毎月の分は一覧で1つの綴りにまとまり、開くと月ごとに並びます。':''),'folders')})}
 const count=(id:string)=>board.posts.filter(p=>p.folder===id).length;
 const actorStyle={'--start-x':(origin.x-window.innerWidth/2)+'px','--start-y':(origin.y-Math.max(90,Math.min(window.innerHeight*.2,180)))+'px'} as CSSProperties;
 return <dialog ref={dialog} className="talkDialog" aria-labelledby="boardTitle" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><div className="encounterActor" style={actorStyle} aria-hidden="true"><span>回覧板</span><img src="/classroom/student-board.png" alt=""/></div><section className="talkPanel boardPanel"><div className="talkHeader"><div><MessageCircle size={18}/><h2 id="boardTitle">回覧板の係</h2><span>{myName?myName+'さんとお話し中'+(isAdmin?'（管理者）':''):'お話し中'}</span></div><button aria-label="会話を閉じて教室に戻る" disabled={busy} onClick={onClose}><X size={23}/></button></div><div className="talkScroll" ref={feed}><div className="conversationLog" role="log" aria-label="会話" aria-live="polite">{lines.map((l,i)=><div key={i} className={'talkLine '+(l.speaker==='student'?'speaker-student':'you')}><small>{l.speaker==='student'?'回覧板の係':'あなた'}</small><p>{l.text}</p></div>)}</div><div className="conversationActions" aria-busy={busy}>
 {step==='who'&&<>{activeStaff.length>0&&<div className="talkPeople">{activeStaff.map(s=><button key={s.id} disabled={busy} onClick={()=>chooseMe(s)}><b>{s.name} さん</b><span>この名前で使う</span></button>)}</div>}<form className="talkInput boardAdd" onSubmit={e=>addStaff(e,true)}><label>{activeStaff.length?'名簿にない場合は、お名前を登録':'職員のお名前'}<input autoFocus={!activeStaff.length} required maxLength={boardLimits.name} placeholder="例：山田" value={staffName} onChange={e=>setStaffName(e.target.value)}/></label><button className="talkPrimary" disabled={busy}><UserPlus size={17}/>登録してこの名前で使う</button></form></>}
 {step==='menu'&&<div className="talkChoices"><button disabled={busy} onClick={()=>openList(unread?'未確認のお知らせを見たい':'回覧板を見たい',unread>0)}>回覧板を見る{unread>0&&<em className="boardCount">未確認 {unread}</em>}</button><button disabled={busy} onClick={startWrite}>お知らせを回す</button><button disabled={busy} onClick={()=>say('フォルダーを整理したい',board.folders.length?'フォルダーの一覧です。名前や色、綴りにするかを変えられます。':'まだフォルダーがありません。よく使う分け方から作れます。','folders')}>フォルダーを整理する</button><button disabled={busy} onClick={()=>say('職員名簿を見たい','「見ました」を確認する職員の名簿です。管理者もここで決めます。','staff')}>職員名簿・管理者</button><button className="boardWho" disabled={busy} onClick={()=>say('名前を切り替えたい','どなたが使いますか？','who')}>使う人を切り替える（いま：{myName}さん）</button></div>}
 {step==='list'&&<><PostList board={board} me={me} filter={filter} setFilter={setFilter} busy={busy} onOpen={openPost}/><button className="talkPrimary" disabled={busy} onClick={startWrite}>お知らせを回す</button></>}
 {step==='post'&&detail&&<PostView key={detail.post.id+':'+detail.post.version+':'+detail.post.target+detail.post.due+detail.post.expires} detail={detail} board={board} me={me} busy={busy} isAdmin={isAdmin} on={{
  read:read=>postAction(read?'見ました':'確認を取り消す',read?'確認を記録しました。ありがとうございます！':'確認の記録を取り消しました。',{action:read?'read':'unread',staff:me}),
  comment:async body=>{let ok=false;const id=detail.post.id;await run(async()=>{await patch({action:'comment',id,staff:me,body});await refreshPost(id);ok=true;setLines(prev=>[...prev,{speaker:'student',text:'コメントを載せました。'}])});return ok},
  deleteComment,pin:v=>postAction(v?'ピン留めする':'ピン留めを外す',v?'一覧の一番上に固定しました。':'ピン留めを外しました。',{action:'pin',pinned:v}),
  archive:v=>postAction(v?'掲載を終える':'回覧板に戻す',v?'掲載を終えました。「掲載終了を見る」からいつでも見られます。':'回覧板に戻しました。',{action:'archive',archived:v}),
  move:folder=>postAction((board.folders.find(f=>f.id===folder)?.name??'フォルダーなし')+'へ移す','フォルダーを移しました。',{action:'move',folder}),
  meta:m=>postAction('対象者・期限を変える','対象者と期限を変えました。',{action:'meta',...m}),
  addVersion:()=>say('新しい版を追加したい','修正したファイルを選んでください。前の版も残ります。','version'),
  remove:()=>{if(!isAdmin){setError(board.hasPin?'削除は管理者だけができます。':'まだ管理者がいません。「職員名簿・管理者」から暗証番号を決めてください。');return}say('このお知らせを削除したい','本当に削除しますか？添付ファイル・確認記録・コメントもすべて消え、元に戻せません。残しておくだけなら「掲載を終える」が使えます。','confirmDelete')},
  back:()=>openList('一覧に戻る')}}/>}
 {step==='confirmDelete'&&detail&&<div className="talkChoices"><button className="boardDanger" disabled={busy} onClick={deletePost}><Trash2 size={16}/>削除する</button><button disabled={busy} onClick={()=>say('やめておく','削除をやめました。','post')}>やめておく</button></div>}
 {step==='version'&&detail&&<VersionForm title={detail.post.title} busy={busy} onSubmit={submitVersion} onCancel={()=>setStep('post')} setError={setError}/>}
 {step==='write'&&<WriteForm board={board} myName={myName} isAdmin={isAdmin} busy={busy} draft={draft} setDraft={setDraft} onSubmit={submitPost} onSaveTemplate={saveTemplate} onDeleteTemplate={deleteTemplate} setError={setError}/>}
 {step==='pin'&&<form onSubmit={submitPin} className="talkInput"><label>管理者の暗証番号<input autoFocus type="password" inputMode="numeric" autoComplete="off" required pattern="\d{4,8}" maxLength={8} value={pinInput} onChange={e=>setPinInput(e.target.value)}/></label><button className="talkPrimary" disabled={busy}><ShieldCheck size={17}/>確認して進む</button></form>}
 {step==='pinSetup'&&<form onSubmit={savePin} className="talkInput">{board.hasPin&&<label>いまの暗証番号<input type="password" inputMode="numeric" autoComplete="off" required pattern="\d{4,8}" maxLength={8} value={pinSetup.current} onChange={e=>setPinSetup({...pinSetup,current:e.target.value})}/></label>}<label>新しい暗証番号（4〜8桁の数字）<input autoFocus type="password" inputMode="numeric" autoComplete="new-password" required pattern="\d{4,8}" maxLength={8} value={pinSetup.next} onChange={e=>setPinSetup({...pinSetup,next:e.target.value})}/></label><label>もう一度<input type="password" inputMode="numeric" autoComplete="new-password" required pattern="\d{4,8}" maxLength={8} value={pinSetup.again} onChange={e=>setPinSetup({...pinSetup,again:e.target.value})}/></label><button className="talkPrimary" disabled={busy}><KeyRound size={17}/>暗証番号を決める</button></form>}
 {step==='folders'&&<>{board.folders.length>0&&<div className="boardFolderList">{board.folders.map(f=><button key={f.id} disabled={busy} style={tagStyle(f.color)} onClick={()=>{setFolderDraft({id:f.id,name:f.name,color:f.color,binder:!!f.binder});say('「'+f.name+'」を変更したい','新しい名前と色を選んでください。','folderEdit')}}><span className="boardTag">{f.binder?<Layers size={12}/>:null}{f.name}</span><small>{count(f.id)} 件{f.binder?' ／ 綴り':''} ／ 変更する</small></button>)}</div>}
  {suggestedFolders.some(s=>!board.folders.some(f=>f.name===s.name))&&<><p className="talkEmpty">よく使う分け方：</p><div className="talkFilters">{suggestedFolders.filter(s=>!board.folders.some(f=>f.name===s.name)).map(s=><button key={s.name} className="boardTag" style={tagStyle(s.color)} disabled={busy} onClick={()=>quickFolder(s.name,s.color,s.binder)}>＋ {s.name}{s.binder?'（綴り）':''}</button>)}</div></>}
  <button className="talkPrimary" disabled={busy} onClick={()=>{setFolderDraft({id:'',name:'',color:'green',binder:false});say('新しいフォルダーを作りたい','フォルダーの名前と色を決めてください。','folderEdit')}}><FolderPlus size={17}/>新しいフォルダーを作る</button></>}
 {step==='folderEdit'&&<form onSubmit={saveFolder} className="talkInput"><label>フォルダー名<input autoFocus required maxLength={boardLimits.name} placeholder="例：シフト集" value={folderDraft.name} onChange={e=>setFolderDraft({...folderDraft,name:e.target.value})}/></label><fieldset className="boardColors"><legend>色</legend>{folderColors.map(c=><label key={c.key} style={tagStyle(c.key)} className={folderDraft.color===c.key?'chosen':''}><input type="radio" name="color" value={c.key} checked={folderDraft.color===c.key} onChange={()=>setFolderDraft({...folderDraft,color:c.key})}/>{c.label}</label>)}</fieldset><label className="boardCheckbox binder"><input type="checkbox" checked={folderDraft.binder} onChange={e=>setFolderDraft({...folderDraft,binder:e.target.checked})}/><Layers size={15}/>綴りにする（シフト集のように、一覧では1つにまとめて、開くと月ごとに並べる）</label><button className="talkPrimary" disabled={busy}>{folderDraft.id?'変更を保存する':'フォルダーを作る'}</button><button type="button" className="talkSecondary" disabled={busy} onClick={()=>setStep('folders')}>フォルダー一覧に戻る</button></form>}
 {step==='staff'&&<><ul className="boardStaff">{board.staff.map(s=><li key={s.id} className={s.active?'':'retired'}><span>{s.name} さん{!!s.admin&&<em className="boardAdmin"><ShieldCheck size={12}/>管理者</em>}{s.id===me&&<small>（いま使っている人）</small>}{!s.active&&<small>（退職・休職）</small>}</span><span className="boardStaffActions">{isAdmin&&s.active&&s.id!==me&&<button className="talkSecondary" disabled={busy} onClick={()=>setStaffAdmin(s,!s.admin)}>{s.admin?'管理者から外す':'管理者にする'}</button>}<button className="talkSecondary" disabled={busy||s.id===me} onClick={()=>setActive(s,!s.active)}>{s.active?'退職・休職にする':'名簿に戻す'}</button></span></li>)}</ul>
  {!board.hasPin?<div className="boardAdminBox"><p>まだ管理者がいません。お知らせの削除は管理者だけができます。暗証番号を決めた人（いまは{myName}さん）が最初の管理者になります。</p><button className="talkSecondary" disabled={busy||!me} onClick={()=>{setPinSetup({current:'',next:'',again:''});say('管理者の暗証番号を決めたい','4〜8桁の数字で暗証番号を決めてください。忘れないようにしてください。','pinSetup')}}><KeyRound size={15}/>暗証番号を決めて管理者になる</button></div>:isAdmin&&<div className="boardAdminBox"><p>管理者は、お知らせ・コメント・テンプレートの削除と、管理者の指定ができます。</p><button className="talkSecondary" disabled={busy} onClick={()=>{setPinSetup({current:'',next:'',again:''});say('暗証番号を変えたい','いまの暗証番号と、新しい暗証番号を入れてください。','pinSetup')}}><KeyRound size={15}/>暗証番号を変える</button></div>}
  <form className="talkInput boardAdd" onSubmit={e=>addStaff(e,false)}><label>職員を追加<input required maxLength={boardLimits.name} placeholder="例：山田" value={staffName} onChange={e=>setStaffName(e.target.value)}/></label><button className="talkPrimary" disabled={busy}><UserPlus size={17}/>名簿に登録する</button></form></>}
 {busy&&<p role="status" className="talkLoading">確認しています…</p>}{error&&<p role="alert" className="talkError">{error}</p>}</div></div><div className="talkFooter"><button disabled={busy} onClick={home}><ChevronLeft size={15}/>最初の会話に戻る</button><button disabled={busy} onClick={onClose}>教室に戻る</button></div></section></dialog>
}
