'use client';
import {useEffect,useRef,useState,type FormEvent,type CSSProperties} from 'react';
import {X,ChevronLeft,Search,Check,MessageCircle,Paperclip,Star,FolderPlus,UserPlus,Download,ExternalLink,Send,Undo2} from 'lucide-react';
import {folderColors,colorOf,suggestedFolders,boardAccept,boardLimits,type Staff,type Folder,type PostSummary,type PostDetail} from '../lib/board';
type Step='who'|'menu'|'list'|'post'|'write'|'folders'|'folderEdit'|'staff';
type Line={speaker:'student'|'you';text:string};
type Board={staff:Staff[];folders:Folder[];posts:PostSummary[]};
export const boardStaffKey='board-staff-id';
const day=(iso:string)=>new Date(iso).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',weekday:'short'});
const stamp=(iso:string)=>new Date(iso).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
const tagStyle=(color:string)=>{const c=colorOf(color);return {'--tag-bg':c.bg,'--tag-ink':c.ink} as CSSProperties};
export default function BoardConversation({origin,onClose}:{origin:{x:number;y:number};onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),feed=useRef<HTMLDivElement>(null),returnFocus=useRef<Element|null>(null);
 const [step,setStep]=useState<Step>('menu'),[lines,setLines]=useState<Line[]>([{speaker:'student',text:'こんにちは。回覧板の係です。'}]);
 const [board,setBoard]=useState<Board>({staff:[],folders:[],posts:[]}),[me,setMe]=useState(''),[detail,setDetail]=useState<PostDetail|null>(null);
 const [folder,setFolder]=useState('all'),[onlyUnread,setOnlyUnread]=useState(false),[onlyImportant,setOnlyImportant]=useState(false),[archived,setArchived]=useState(false),[query,setQuery]=useState('');
 const [draft,setDraft]=useState({title:'',body:'',folder:'',important:false}),[folderDraft,setFolderDraft]=useState({id:'',name:'',color:'green'}),[staffName,setStaffName]=useState('');
 const [busy,setBusy]=useState(true),[error,setError]=useState('');
 const myName=board.staff.find(s=>s.id===me)?.name??'';
 const activeStaff=board.staff.filter(s=>s.active);
 const unread=board.posts.filter(p=>!p.archived&&!p.seen).length;
 useEffect(()=>{returnFocus.current=document.activeElement;dialog.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;(returnFocus.current as HTMLElement)?.focus?.()}},[]);
 useEffect(()=>{if(step==='post'){feed.current?.querySelector('.boardPost')?.scrollIntoView({block:'start'});return}feed.current?.scrollTo({top:feed.current.scrollHeight,behavior:'instant'})},[lines,step,error]);
 useEffect(()=>{let saved='';try{saved=localStorage.getItem(boardStaffKey)||''}catch{}void (async()=>{try{const data=await load(saved);const known=data.staff.some(s=>s.active&&s.id===saved);if(known){setMe(saved);const n=data.posts.filter(p=>!p.archived&&!p.seen).length;setLines([{speaker:'student',text:'こんにちは、'+data.staff.find(s=>s.id===saved)!.name+'さん。回覧板の係です。'+(n?'まだ確認していないお知らせが '+n+' 件あります。':'新しいお知らせはすべて確認済みです。')}])}else{setLines([{speaker:'student',text:data.staff.length?'こんにちは。回覧板の係です。まず、あなたのお名前を選んでください。「見ました」の記録に使います。':'こんにちは。回覧板の係です。はじめに、職員のお名前を登録しましょう。「見ました」の記録に使います。'}]);setStep('who')}}catch(e){setError((e as Error).message)}finally{setBusy(false)}})()},[]);
 // eslint-disable-next-line @typescript-eslint/no-explicit-any -- 呼び出し側で型を付ける（StudentConversationと同じ）
 async function api(url:string,init?:RequestInit):Promise<any>{const r=await fetch(url,init);const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error||'処理できませんでした。もう一度お試しください。');return data;}
 const patch=(body:object)=>api('/api/board',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 async function load(staff=me){const data:Board=await api('/api/board?staff='+encodeURIComponent(staff));setBoard(data);return data;}
 function say(user:string,reply:string,next:Step){setError('');setLines(prev=>[...prev,{speaker:'you',text:user},{speaker:'student',text:reply}]);setStep(next)}
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function home(){if(!me){setStep('who');return}setError('');setStep('menu');setLines([{speaker:'student',text:'ほかに、お手伝いできることはありますか？'+(unread?'（未確認 '+unread+' 件）':'')}])}
 function chooseMe(s:Staff){setMe(s.id);try{localStorage.setItem(boardStaffKey,s.id)}catch{}void run(async()=>{const data=await load(s.id);const n=data.posts.filter(p=>!p.archived&&!p.seen).length;say(s.name+' です',s.name+'さんですね。'+(n?'まだ確認していないお知らせが '+n+' 件あります。':'新しいお知らせはありません。')+'何をしましょうか？','menu')})}
 function addStaff(e:FormEvent,thenChoose:boolean){e.preventDefault();const name=staffName.trim();if(!name)return;void run(async()=>{const s:Staff=await patch({action:'staff',name});setStaffName('');await load();if(thenChoose)chooseMe(s);else say(name+' さんを登録','名簿に '+name+' さんを登録しました。','staff')})}
 function setActive(s:Staff,active:boolean){void run(async()=>{await patch({action:'staff',id:s.id,active});await load();say(s.name+(active?' さんを名簿に戻す':' さんを退職にする'),active?s.name+' さんを名簿に戻しました。':s.name+' さんを「まだの人」から外しました。これまでの「見ました」の記録は残っています。','staff')})}
 function openList(label:string,unreadOnly=false){setFolder('all');setOnlyUnread(unreadOnly);setOnlyImportant(false);setArchived(false);setQuery('');void run(async()=>{const data=await load();say(label,data.posts.some(p=>!p.archived)?'お知らせの一覧です。フォルダーや検索で探せます。':'まだお知らせはありません。最初のお知らせを回してみましょう。','list')})}
 function openPost(p:PostSummary){void run(async()=>{const d:PostDetail=await api('/api/board?post='+p.id);setDetail(d);say(p.title,p.seen?'こちらのお知らせです。確認済みです。':'こちらのお知らせです。読んだら「見ました」を押してください。','post')})}
 async function refreshPost(id:string){const [d]=await Promise.all([api('/api/board?post='+id),load()]);setDetail(d);}
 function markRead(read:boolean){const id=detail!.post.id;void run(async()=>{await patch({action:read?'read':'unread',id,staff:me});await refreshPost(id);say(read?'見ました':'確認を取り消す',read?'確認を記録しました。ありがとうございます！':'確認の記録を取り消しました。','post')})}
 function archive(value:boolean){const id=detail!.post.id;void run(async()=>{await patch({action:'archive',id,archived:value});await refreshPost(id);say(value?'掲載を終える':'掲示に戻す',value?'掲載を終えました。「掲載終了」からいつでも見られます。':'回覧板に戻しました。','post')})}
 function move(folderId:string){const id=detail!.post.id;void run(async()=>{await patch({action:'move',id,folder:folderId});await refreshPost(id);const f=board.folders.find(f=>f.id===folderId);say((f?.name??'フォルダーなし')+'へ移す','「'+(f?.name??'フォルダーなし')+'」に移しました。','post')})}
 function startWrite(){setDraft({title:'',body:'',folder:folder!=='all'&&folder!=='none'?folder:'',important:false});say('お知らせを回したい','件名と内容を書いてください。シフト表などのPDFも付けられます。','write')}
 function submitPost(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const files=f.getAll('file').filter((x):x is File=>x instanceof File&&x.size>0);
  if(files.length>boardLimits.files){setError('添付ファイルは5つまでです。');return}if(files.some(x=>x.size>boardLimits.fileSize)){setError('添付ファイルは1つ20 MBまでです。');return}if(files.reduce((n,x)=>n+x.size,0)>boardLimits.total){setError('添付ファイルは合計50 MBまでです。');return}
  if(!draft.body.trim()&&!files.length){setError('本文か添付ファイルのどちらかを入れてください。');return}
  f.set('author',me);f.set('important',draft.important?'1':'0');
  void run(async()=>{const {id}=await api('/api/board',{method:'POST',body:f});const d:PostDetail=await api('/api/board?post='+id);await load();setDetail(d);say(draft.title.trim(),'回覧板に載せました。だれが見たかは、この画面でいつでも確認できます。','post')})}
 function saveFolder(e:FormEvent){e.preventDefault();void run(async()=>{const f:Folder=await patch({action:'folder',...folderDraft,name:folderDraft.name.trim()});await load();say(f.name,folderDraft.id?'「'+f.name+'」を変更しました。':'「'+f.name+'」フォルダーを作りました。','folders')})}
 function quickFolder(name:string,color:string){void run(async()=>{await patch({action:'folder',name,color});await load();say(name+' フォルダーを作る','「'+name+'」フォルダーを作りました。','folders')})}
 const words=query.trim().toLowerCase().split(/\s+/).filter(Boolean);
 const visible=board.posts.filter(p=>!!p.archived===archived&&(folder==='all'||(folder==='none'?!p.folder:p.folder===folder))&&(!onlyUnread||!p.seen)&&(!onlyImportant||p.important)&&words.every(w=>(p.title+' '+p.body+' '+p.author+' '+(p.fileNames??'')).toLowerCase().includes(w)));
 const count=(id:string)=>board.posts.filter(p=>!p.archived&&(id==='none'?!p.folder:p.folder===id)).length;
 const folderOf=(id:string|null)=>board.folders.find(f=>f.id===id);
 const actorStyle={'--start-x':(origin.x-window.innerWidth/2)+'px','--start-y':(origin.y-Math.max(90,Math.min(window.innerHeight*.2,180)))+'px'} as CSSProperties;
 const pending=detail?activeStaff.filter(s=>!detail.reads.some(r=>r.staff===s.id)):[];
 const mine=detail?.reads.find(r=>r.staff===me);
 return <dialog ref={dialog} className="talkDialog" aria-labelledby="boardTitle" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><div className="encounterActor" style={actorStyle} aria-hidden="true"><span>回覧板</span><img src="/classroom/student-board.png" alt=""/></div><section className="talkPanel"><div className="talkHeader"><div><MessageCircle size={18}/><h2 id="boardTitle">回覧板の係</h2><span>{myName?myName+'さんとお話し中':'お話し中'}</span></div><button aria-label="会話を閉じて教室に戻る" disabled={busy} onClick={onClose}><X size={23}/></button></div><div className="talkScroll" ref={feed}><div className="conversationLog" role="log" aria-label="会話" aria-live="polite">{lines.map((l,i)=><div key={i} className={'talkLine '+(l.speaker==='student'?'speaker-student':'you')}><small>{l.speaker==='student'?'回覧板の係':'あなた'}</small><p>{l.text}</p></div>)}</div><div className="conversationActions" aria-busy={busy}>
 {step==='who'&&<>{activeStaff.length>0&&<div className="talkPeople">{activeStaff.map(s=><button key={s.id} disabled={busy} onClick={()=>chooseMe(s)}><b>{s.name} さん</b><span>この名前で使う</span></button>)}</div>}<form className="talkInput boardAdd" onSubmit={e=>addStaff(e,true)}><label>{activeStaff.length?'名簿にない場合は、お名前を登録':'職員のお名前'}<input autoFocus={!activeStaff.length} required maxLength={boardLimits.name} placeholder="例：山田" value={staffName} onChange={e=>setStaffName(e.target.value)}/></label><button className="talkPrimary" disabled={busy}><UserPlus size={17}/>登録してこの名前で使う</button></form></>}
 {step==='menu'&&<div className="talkChoices"><button disabled={busy} onClick={()=>openList(unread?'未確認のお知らせを見たい':'回覧板を見たい',unread>0)}>回覧板を見る{unread>0&&<em className="boardCount">未確認 {unread}</em>}</button><button disabled={busy} onClick={startWrite}>お知らせを回す</button><button disabled={busy} onClick={()=>say('フォルダーを整理したい',board.folders.length?'フォルダーの一覧です。名前や色を変えたり、新しく作ったりできます。':'まだフォルダーがありません。よく使う分け方から作れます。','folders')}>フォルダーを整理する</button><button disabled={busy} onClick={()=>say('職員名簿を見たい','「見ました」を確認する職員の名簿です。','staff')}>職員名簿</button><button className="boardWho" disabled={busy} onClick={()=>say('名前を切り替えたい','どなたが使いますか？','who')}>使う人を切り替える（いま：{myName}さん）</button></div>}
 {step==='list'&&<><label className="talkSearch"><Search size={17}/><input aria-label="件名・本文・ファイル名で検索" value={query} onChange={e=>setQuery(e.target.value)} placeholder="件名・本文・ファイル名・書いた人で検索"/></label><div className="talkFilters boardFolders" role="group" aria-label="フォルダー"><button className={folder==='all'?'selected':''} aria-pressed={folder==='all'} onClick={()=>setFolder('all')}>すべて</button>{board.folders.map(f=><button key={f.id} className={'boardTag'+(folder===f.id?' selected':'')} aria-pressed={folder===f.id} style={tagStyle(f.color)} onClick={()=>setFolder(f.id)}>{f.name}<small>{count(f.id)}</small></button>)}{board.posts.some(p=>!p.folder)&&<button className={folder==='none'?'selected':''} aria-pressed={folder==='none'} onClick={()=>setFolder('none')}>フォルダーなし<small>{count('none')}</small></button>}</div><div className="boardToggles"><label><input type="checkbox" checked={onlyUnread} onChange={e=>setOnlyUnread(e.target.checked)}/>未確認だけ</label><label><input type="checkbox" checked={onlyImportant} onChange={e=>setOnlyImportant(e.target.checked)}/>重要だけ</label><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>掲載終了を見る</label></div>
  <div className="boardList">{visible.map(p=>{const f=folderOf(p.folder);return <button key={p.id} className={'boardItem'+(p.seen?'':' unseen')} style={tagStyle(f?.color??'gray')} disabled={busy} onClick={()=>openPost(p)}><span className="boardItemHead">{f?<span className="boardTag">{f.name}</span>:<span className="boardTag plain">フォルダーなし</span>}{!!p.important&&<span className="boardImportant"><Star size={12}/>重要</span>}{!p.seen&&<span className="boardNew">未確認</span>}</span><b>{p.title}</b><span className="boardMeta"><span>{day(p.created)}</span><span>{p.author}</span>{p.files>0&&<span><Paperclip size={13}/>{p.files}</span>}<span className={p.reads>=activeStaff.length?'done':''}><Check size={13}/>確認 {p.reads}/{activeStaff.length}人</span></span></button>})}</div>
  {!visible.length&&<p className="talkEmpty">{board.posts.length?'条件に合うお知らせはありません。':'まだお知らせはありません。'}</p>}<button className="talkPrimary" disabled={busy} onClick={startWrite}><Send size={16}/>お知らせを回す</button></>}
 {step==='post'&&detail&&(()=>{const p=detail.post,f=folderOf(p.folder);return <><article className="boardPost" style={tagStyle(f?.color??'gray')}><div className="boardItemHead">{f?<span className="boardTag">{f.name}</span>:<span className="boardTag plain">フォルダーなし</span>}{!!p.important&&<span className="boardImportant"><Star size={12}/>重要</span>}{!!p.archived&&<span className="boardTag plain">掲載終了</span>}</div><h3>{p.title}</h3><p className="boardMeta"><span>{stamp(p.created)}</span><span>{p.author} さんが回しました</span></p>{p.body&&<p className="boardBody">{p.body}</p>}
  {detail.files.length>0&&<ul className="boardFiles">{detail.files.map(x=>{const view=/\.(pdf|png|jpe?g|webp)$/i.test(x.name);return <li key={x.id}><Paperclip size={16}/><span>{x.name}<small>{x.size<1024*1024?Math.max(1,Math.round(x.size/1024))+' KB':(x.size/1024/1024).toFixed(1)+' MB'}</small></span>{view&&<a href={'/api/board/files/'+x.id} target="_blank" rel="noopener"><ExternalLink size={15}/>開く</a>}<a href={'/api/board/files/'+x.id+'?download=1'}><Download size={15}/>保存</a></li>})}</ul>}
  <div className="boardCheck">{mine?<><p><Check size={18}/>{myName}さんは {stamp(mine.readAt)} に確認しました</p><button className="talkSecondary" disabled={busy} onClick={()=>markRead(false)}><Undo2 size={15}/>確認を取り消す</button></>:<button className="boardSeen" disabled={busy||!me} onClick={()=>markRead(true)}><Check size={22}/>見ました</button>}</div>
  <div className="boardReads"><div><h4>見た人 <span>{detail.reads.length}</span></h4><ul>{detail.reads.map(r=><li key={r.staff}>{r.name}<small>{stamp(r.readAt)}</small></li>)}</ul></div><div><h4>まだの人 <span>{pending.length}</span></h4>{pending.length?<ul>{pending.map(s=><li key={s.id} className="pending">{s.name}</li>)}</ul>:<p>全員が確認しました。</p>}</div></div></article>
  <div className="boardPostActions"><button className="talkSecondary" disabled={busy} onClick={()=>openList('一覧に戻る')}>一覧に戻る</button><label className="boardMove">フォルダーを移す<select disabled={busy} value={p.folder??''} onChange={e=>move(e.target.value)}><option value="">フォルダーなし</option>{board.folders.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="talkSecondary" disabled={busy} onClick={()=>archive(!p.archived)}>{p.archived?'回覧板に戻す':'掲載を終える'}</button></div></>})()}
 {step==='write'&&<form onSubmit={submitPost} className="talkInput boardWrite"><label>フォルダー<select name="folder" value={draft.folder} onChange={e=>setDraft({...draft,folder:e.target.value})}><option value="">フォルダーなし</option>{board.folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>件名<input autoFocus name="title" required maxLength={boardLimits.title} placeholder="例：10月のシフト表" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>内容<textarea name="body" rows={4} maxLength={boardLimits.body} placeholder="例：10月のシフトです。変更がある方は15日までに伝えてください。" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><label className="talkFile"><Paperclip size={22}/><span>ファイルを付ける（任意）</span><input type="file" name="file" multiple accept={boardAccept}/><small>PDF・Word・Excel・画像・テキスト ／ 5つまで・1つ20 MBまで</small></label><label className="boardCheckbox"><input type="checkbox" checked={draft.important} onChange={e=>setDraft({...draft,important:e.target.checked})}/><Star size={15}/>重要なお知らせにする</label><div className="talkSelected">書いた人：{myName} さん</div><button className="talkPrimary" disabled={busy}><Send size={16}/>{busy?'送っています…':'回覧板に載せる'}</button></form>}
 {step==='folders'&&<>{board.folders.length>0&&<div className="boardFolderList">{board.folders.map(f=><button key={f.id} disabled={busy} style={tagStyle(f.color)} onClick={()=>{setFolderDraft({id:f.id,name:f.name,color:f.color});say('「'+f.name+'」を変更したい','新しい名前と色を選んでください。','folderEdit')}}><span className="boardTag">{f.name}</span><small>{count(f.id)} 件 ／ 変更する</small></button>)}</div>}
  {suggestedFolders.some(s=>!board.folders.some(f=>f.name===s.name))&&<><p className="talkEmpty">よく使う分け方：</p><div className="talkFilters">{suggestedFolders.filter(s=>!board.folders.some(f=>f.name===s.name)).map(s=><button key={s.name} className="boardTag" style={tagStyle(s.color)} disabled={busy} onClick={()=>quickFolder(s.name,s.color)}>＋ {s.name}</button>)}</div></>}
  <button className="talkPrimary" disabled={busy} onClick={()=>{setFolderDraft({id:'',name:'',color:'green'});say('新しいフォルダーを作りたい','フォルダーの名前と色を決めてください。','folderEdit')}}><FolderPlus size={17}/>新しいフォルダーを作る</button></>}
 {step==='folderEdit'&&<form onSubmit={saveFolder} className="talkInput"><label>フォルダー名<input autoFocus required maxLength={boardLimits.name} placeholder="例：シフト表" value={folderDraft.name} onChange={e=>setFolderDraft({...folderDraft,name:e.target.value})}/></label><fieldset className="boardColors"><legend>色</legend>{folderColors.map(c=><label key={c.key} style={tagStyle(c.key)} className={folderDraft.color===c.key?'chosen':''}><input type="radio" name="color" value={c.key} checked={folderDraft.color===c.key} onChange={()=>setFolderDraft({...folderDraft,color:c.key})}/>{c.label}</label>)}</fieldset><button className="talkPrimary" disabled={busy}>{folderDraft.id?'変更を保存する':'フォルダーを作る'}</button><button type="button" className="talkSecondary" disabled={busy} onClick={()=>setStep('folders')}>フォルダー一覧に戻る</button></form>}
 {step==='staff'&&<><ul className="boardStaff">{board.staff.map(s=><li key={s.id} className={s.active?'':'retired'}><span>{s.name} さん{s.id===me&&<small>（いま使っている人）</small>}{!s.active&&<small>（退職・休職）</small>}</span><button className="talkSecondary" disabled={busy||s.id===me} onClick={()=>setActive(s,!s.active)}>{s.active?'退職・休職にする':'名簿に戻す'}</button></li>)}</ul><form className="talkInput boardAdd" onSubmit={e=>addStaff(e,false)}><label>職員を追加<input required maxLength={boardLimits.name} placeholder="例：山田" value={staffName} onChange={e=>setStaffName(e.target.value)}/></label><button className="talkPrimary" disabled={busy}><UserPlus size={17}/>名簿に登録する</button></form></>}
 {busy&&<p role="status" className="talkLoading">確認しています…</p>}{error&&<p role="alert" className="talkError">{error}</p>}</div></div><div className="talkFooter"><button disabled={busy} onClick={home}><ChevronLeft size={15}/>最初の会話に戻る</button><button disabled={busy} onClick={onClose}>教室に戻る</button></div></section></dialog>
}
