'use client';
import {useEffect,useRef,useState,type FormEvent,type CSSProperties} from 'react';
import {X,ChevronLeft,FileText,Upload,Download,Search,Check,MessageCircle} from 'lucide-react';
import {profileFields,type Profile} from '../lib/profile';
type Person={id:string;name:string;city:string;count:number};
type Doc={id:string;name:string;category:string;size:number;created:string};
type Step='menu'|'people'|'name'|'city'|'confirm'|'person'|'documents'|'category'|'upload'|'edit'|'profile';
type Line={speaker:'student'|'you';text:string};
export const documentKinds=['個別支援計画','原案','本案','会議議事録','アセスメント','モニタリング'];
export default function StudentConversation({origin,onClose}:{origin:{x:number;y:number};onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),feed=useRef<HTMLDivElement>(null),returnFocus=useRef<Element|null>(null);
 const [step,setStep]=useState<Step>('menu'),[lines,setLines]=useState<Line[]>([{speaker:'student',text:'こんにちは。利用者情報の係です。今日は何をお手伝いしましょうか？'}]);
 const [people,setPeople]=useState<Person[]>([]),[person,setPerson]=useState<Person|null>(null),[docs,setDocs]=useState<Doc[]>([]),[query,setQuery]=useState(''),[name,setName]=useState(''),[city,setCity]=useState(''),[category,setCategory]=useState(documentKinds[0]),[filter,setFilter]=useState('すべて'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [profile,setProfile]=useState<Profile>({}),[basicIntent,setBasicIntent]=useState(false);
 useEffect(()=>{returnFocus.current=document.activeElement;dialog.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;(returnFocus.current as HTMLElement)?.focus?.()}},[]);
 useEffect(()=>{if(step==='profile'){feed.current?.querySelector('.talkProfile')?.scrollIntoView({block:'start'});return}feed.current?.scrollTo({top:feed.current.scrollHeight,behavior:'instant'})},[lines,step,error]);
 async function api(url:string,init?:RequestInit){const r=await fetch(url,init);const data:any=await r.json();if(!r.ok)throw Error(data.error||'処理できませんでした。もう一度お試しください。');return data;}
 function say(user:string,reply:string,next:Step){setError('');setLines(prev=>[...prev,{speaker:'you',text:user},{speaker:'student',text:reply}]);setStep(next)}
 function home(){setError('');setStep('menu');setLines([{speaker:'student',text:'ほかに、お手伝いできることはありますか？'}])}
 async function choosePeople(label:string,basic=false){setBasicIntent(basic);setBusy(true);setError('');try{const data=await api('/api/records');setPeople(data);setQuery('');say(label,data.length?'利用者様を選んでください。氏名や市区町村で絞り込めます。':'まだ利用者様が登録されていません。最初の一人を登録しましょう。','people')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function startRegistration(){setName('');setCity('');say('利用者を登録したい','まず、利用者様のお名前を教えてください。','name')}
 function selectPerson(p:Person){setPerson(p);if(basicIntent){void showProfile(p);return;}say(p.name+' 様',p.name+' 様ですね。市区町村は「'+p.city+'」です。どちらをご案内しましょうか？','person')}
 async function showProfile(p:Person){setBusy(true);setError('');try{const data=await api('/api/profile?person='+p.id);setPerson(p);setProfile(data);say(p.name+' 様の基本情報',p.name+' 様の基本情報です。生年月日や住所、連絡先を確認できます。','profile')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function register(){setBusy(true);setError('');try{const p=await api('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),city:city.trim()})});setPerson({...p,count:0});say('この内容で登録する',p.name+' 様を登録しました。このまま支援書類も保存できます。','person')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function showDocuments(){setBusy(true);setError('');try{const data=await api('/api/records?person='+person!.id);setDocs(data);setFilter('すべて');say('支援書類を見たい',data.length?person!.name+' 様の書類です。種類を選んで探せます。':'まだ書類はありません。「書類を保存する」から追加できます。','documents')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function startUpload(){say('書類を保存したい','どの種類の書類を保存しますか？','category')}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const file=f.get('file');if(!(file instanceof File)||file.size>20*1024*1024){setError('20 MB以下のファイルを選んでください。');return}f.set('person',person!.id);f.set('category',category);setBusy(true);setError('');try{await api('/api/records',{method:'PUT',body:f});say(file.name,person!.name+' 様の「'+category+'」に保存しました。以前の書類もそのまま残っています。','person')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function edit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const p=await api('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:person!.id,name:name.trim(),city:city.trim()})});setPerson({...person!,...p});say('情報を更新する','利用者情報を更新しました。','person')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function nextName(e:FormEvent){e.preventDefault();if(!name.trim())return;setName(name.trim());say(name.trim(),name.trim()+' 様ですね。次に、市区町村を教えてください。','city')}
 function nextCity(e:FormEvent){e.preventDefault();if(!city.trim())return;setCity(city.trim());say(city.trim(),'こちらの内容で登録してよろしいですか？','confirm')}
 const actorStyle={'--start-x':(origin.x-window.innerWidth/2)+'px','--start-y':(origin.y-Math.max(90,Math.min(window.innerHeight*.2,180)))+'px'} as CSSProperties;
 return <dialog ref={dialog} className="talkDialog" aria-labelledby="talkTitle" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><div className="encounterActor" style={actorStyle} aria-hidden="true"><span>利用者情報</span><img src="/classroom/student-chunky.png" alt=""/></div><section className="talkPanel"><div className="talkHeader"><div><MessageCircle size={18}/><h2 id="talkTitle">利用者情報の係</h2><span>お話し中</span></div><button aria-label="会話を閉じて教室に戻る" disabled={busy} onClick={onClose}><X size={23}/></button></div><div className="talkScroll" ref={feed}><div className="conversationLog" role="log" aria-label="会話" aria-live="polite">{lines.map((l,i)=><div key={i} className={'talkLine '+(l.speaker==='student'?'speaker-student':'you')}><small>{l.speaker==='student'?'利用者情報の係':'あなた'}</small><p>{l.text}</p></div>)}</div><div className="conversationActions" aria-busy={busy}>
 {step==='menu'&&<div className="talkChoices"><button disabled={busy} onClick={()=>choosePeople('利用者各基本情報を見たい',true)}>利用者各基本情報</button><button disabled={busy} onClick={()=>choosePeople('利用者を探したい')}>利用者を探す</button><button disabled={busy} onClick={startRegistration}>利用者を登録する</button><button disabled={busy} onClick={()=>choosePeople('支援書類を確認・保存したい')}>支援書類を確認・保存する</button><a href="/users">利用者一覧の画面を開く</a></div>}
 {step==='people'&&<><label className="talkSearch"><Search size={17}/><input autoFocus aria-label="氏名・市区町村で検索" value={query} onChange={e=>setQuery(e.target.value)} placeholder="氏名・市区町村で検索"/></label><div className="talkPeople">{people.filter(p=>(p.name+' '+p.city).includes(query)).map(p=><button key={p.id} disabled={busy} onClick={()=>selectPerson(p)}><b>{p.name} 様</b><span>{p.city}</span></button>)}</div>{people.length>0&&!people.some(p=>(p.name+' '+p.city).includes(query))&&<p className="talkEmpty">該当する利用者様が見つかりません。</p>}<button className="talkSecondary" onClick={startRegistration}>新しく利用者を登録する</button></>}
 {step==='name'&&<form onSubmit={nextName} className="talkInput"><label>利用者氏名<input autoFocus required maxLength={100} placeholder="例：山田 太郎" value={name} onChange={e=>setName(e.target.value)}/></label><button className="talkPrimary">この名前で進む</button></form>}
 {step==='city'&&<form onSubmit={nextCity} className="talkInput"><label>市区町村<input autoFocus required maxLength={100} placeholder="例：横浜市" value={city} onChange={e=>setCity(e.target.value)}/></label><button className="talkPrimary">内容を確認する</button><button type="button" className="talkSecondary" onClick={()=>say('名前を修正したい','お名前を入力し直してください。','name')}>名前を修正する</button></form>}
 {step==='confirm'&&<><dl className="talkSummary"><div><dt>利用者氏名</dt><dd>{name} 様</dd></div><div><dt>市区町村</dt><dd>{city}</dd></div></dl><button className="talkPrimary" disabled={busy} onClick={register}><Check size={17}/>この内容で登録する</button><button className="talkSecondary" disabled={busy} onClick={()=>say('入力を修正したい','お名前から確認しましょう。','name')}>入力を修正する</button></>}
 {step==='person'&&<div className="talkChoices"><button disabled={busy} onClick={()=>showProfile(person!)}>基本情報を見る</button><button disabled={busy} onClick={showDocuments}>支援書類を見る</button><button disabled={busy} onClick={startUpload}>書類を保存する</button><button disabled={busy} onClick={()=>{setName(person!.name);setCity(person!.city);say('利用者情報を編集したい','氏名と市区町村を編集できます。','edit')}}>利用者情報を編集する</button><button disabled={busy} onClick={()=>choosePeople('別の利用者を選びたい')}>別の利用者を選ぶ</button></div>}
 {step==='profile'&&<><div className="talkProfile"><h3>{person!.name} 様の基本情報</h3><dl><div><dt>請求先の市区町村</dt><dd>{person!.city}</dd></div>{profileFields.map(f=><div key={f.key}><dt>{f.label}</dt><dd>{profile[f.key]||(f.key==='phone'&&profile.phoneUnavailable?'取込時に非表示':'未登録')}</dd></div>)}</dl><p>住所はノービーの住所欄の登録内容です。</p></div><button className="talkSecondary" disabled={busy} onClick={()=>choosePeople('別の利用者の基本情報を見たい',true)}>別の利用者の基本情報を見る</button></>}
 {step==='documents'&&<><div className="talkFilters">{['すべて',...documentKinds].map(c=><button key={c} className={filter===c?'selected':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="talkDocuments">{docs.filter(d=>filter==='すべて'||d.category===filter).map(d=><a key={d.id} href={'/api/files/'+d.id}><FileText size={20}/><div><small>{d.category}</small><b>{d.name}</b><small>{new Date(d.created).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo'})} 保存</small></div><Download size={18}/></a>)}</div>{!docs.some(d=>filter==='すべて'||d.category===filter)&&<p className="talkEmpty">この種類の書類はまだありません。</p>}<button className="talkPrimary" onClick={startUpload}><Upload size={17}/>書類を保存する</button></>}
 {step==='category'&&<div className="talkChoices categories">{documentKinds.map(c=><button key={c} onClick={()=>{setCategory(c);say(c,'「'+c+'」ですね。保存するファイルを選んでください。','upload')}}>{c}</button>)}</div>}
 {step==='upload'&&<form onSubmit={upload} className="talkInput"><div className="talkSelected">{person!.name} 様 ／ {category}</div><label className="talkFile"><Upload size={25}/><span>ファイルを選択</span><input autoFocus type="file" name="file" required accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.webp,.txt"/><small>PDF・Word・Excel・画像・テキスト ／ 20 MBまで</small></label><button className="talkPrimary" disabled={busy}>{busy?'保存中…':'この書類を保存する'}</button><button type="button" className="talkSecondary" disabled={busy} onClick={()=>setStep('category')}>書類の種類を選び直す</button></form>}
 {step==='edit'&&<form onSubmit={edit} className="talkInput"><label>利用者氏名<input autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>市区町村<input required maxLength={100} value={city} onChange={e=>setCity(e.target.value)}/></label><button className="talkPrimary" disabled={busy}>変更を保存する</button></form>}
 {busy&&<p role="status" className="talkLoading">確認しています…</p>}{error&&<p role="alert" className="talkError">{error}</p>}</div></div><div className="talkFooter"><button disabled={busy} onClick={home}><ChevronLeft size={15}/>最初の会話に戻る</button><button disabled={busy} onClick={onClose}>教室に戻る</button></div></section></dialog>
}


