'use client';
import {useState,type FormEvent} from 'react';
import {Paperclip,Star,Pin,Send,BookmarkPlus,FileText,X,Clock,CalendarClock,Users} from 'lucide-react';
import {boardAccept,boardLimits,builtinTemplates,fillTemplate,todayJST,addDays,type Board,type Template} from '../../lib/board';
export type Draft={title:string;body:string;folder:string;target:string;due:string;expires:string;forever:boolean;important:boolean;pinned:boolean};
export const emptyDraft=(folder=''):Draft=>({title:'',body:'',folder,target:'',due:'',expires:'',forever:true,important:false,pinned:false});
// 添付ファイルの上限を画面でも先に確かめる
export function checkFiles(files:File[]){if(files.length>boardLimits.files)return '添付ファイルは5つまでです。';if(files.some(x=>x.size>boardLimits.fileSize))return '添付ファイルは1つ20 MBまでです。';if(files.reduce((n,x)=>n+x.size,0)>boardLimits.total)return '添付ファイルは合計50 MBまでです。';return ''}
const monthEnd=()=>{const t=todayJST();const [y,m]=t.split('-').map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)};
export function WriteForm({board,myName,isAdmin,busy,draft,setDraft,onSubmit,onSaveTemplate,onDeleteTemplate,setError}:{board:Board;myName:string;isAdmin:boolean;busy:boolean;draft:Draft;setDraft:(d:Draft)=>void;onSubmit:(form:FormData,files:File[])=>void;onSaveTemplate:(name:string)=>void;onDeleteTemplate:(t:Template)=>void;setError:(e:string)=>void}){
 const [saving,setSaving]=useState(false),[templateName,setTemplateName]=useState('');
 const set=(patch:Partial<Draft>)=>setDraft({...draft,...patch});
 function apply(t:Omit<Template,'id'>){const folder=t.folder&&board.folders.some(f=>f.id===t.folder)?t.folder:board.folders.find(f=>f.name===(t.name==='シフト表'?'シフト集':t.name))?.id??draft.folder;set({title:fillTemplate(t.title),body:fillTemplate(t.body),target:t.target,folder})}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const files=form.getAll('file').filter((x):x is File=>x instanceof File&&x.size>0);const problem=checkFiles(files);if(problem){setError(problem);return}if(!draft.body.trim()&&!files.length){setError('本文か添付ファイルのどちらかを入れてください。');return}if(!draft.forever&&!draft.expires){setError('掲載期限の日付を選ぶか、「無期限」にしてください。');return}form.set('important',draft.important?'1':'0');form.set('pinned',draft.pinned?'1':'0');form.set('expires',draft.forever?'':draft.expires);onSubmit(form,files)}
 const names=board.staff.filter(s=>s.active).map(s=>s.name);
 return <form onSubmit={submit} className="talkInput boardWrite">
  <div className="boardTemplates"><span><FileText size={15}/>テンプレートから書く</span><div>{builtinTemplates.map(t=><button type="button" key={t.name} disabled={busy} onClick={()=>apply(t)}>{t.name}</button>)}{board.templates.map(t=><span key={t.id} className="boardCustomTemplate"><button type="button" disabled={busy} onClick={()=>apply(t)}>{t.name}</button>{isAdmin&&<button type="button" aria-label={'テンプレート「'+t.name+'」を削除'} disabled={busy} onClick={()=>onDeleteTemplate(t)}><X size={13}/></button>}</span>)}</div></div>
  <label>フォルダー<select name="folder" value={draft.folder} onChange={e=>set({folder:e.target.value})}><option value="">フォルダーなし</option>{board.folders.map(f=><option key={f.id} value={f.id}>{f.name}{f.binder?'（綴り）':''}</option>)}</select></label>
  <label>件名<input name="title" required maxLength={boardLimits.title} placeholder="例：10月のシフト表" value={draft.title} onChange={e=>set({title:e.target.value})}/></label>
  <label>内容<textarea name="body" rows={4} maxLength={boardLimits.body} placeholder="例：10月のシフトです。変更がある方は15日までに伝えてください。" value={draft.body} onChange={e=>set({body:e.target.value})}/></label>
  <label><span className="boardLabel"><Users size={15}/>対象者（空欄なら全員）</span><input name="target" maxLength={boardLimits.target} placeholder="例：山田さん、佐藤さん／午前の担当" value={draft.target} onChange={e=>set({target:e.target.value})}/><small className="boardHelp">名簿の名前が入っていれば、その人だけが「まだの人」に出ます。名前が無い書き方（例：午前の担当）は、全員に表示されます。</small></label>
  {names.length>0&&<div className="boardNameChips" aria-label="名前を対象者に入れる">{names.map(n=><button type="button" key={n} disabled={draft.target.includes(n)} onClick={()=>set({target:(draft.target.trim()?draft.target.trim()+'、':'')+n})}>＋{n}</button>)}</div>}
  <label className="boardHalf"><span className="boardLabel"><Clock size={15}/>確認期限（任意）</span><input type="date" name="due" min={todayJST()} value={draft.due} onChange={e=>set({due:e.target.value})}/></label>
  <fieldset className="boardHalf boardExpires"><legend><CalendarClock size={15}/>掲載期限</legend><label><input type="radio" checked={draft.forever} onChange={()=>set({forever:true})}/>無期限</label><label><input type="radio" checked={!draft.forever} onChange={()=>set({forever:false,expires:draft.expires||monthEnd()})}/>日付まで</label>{!draft.forever&&<><input type="date" aria-label="掲載期限の日付" min={todayJST()} value={draft.expires} onChange={e=>set({expires:e.target.value})}/><span className="boardQuick"><button type="button" onClick={()=>set({expires:monthEnd()})}>今月末</button><button type="button" onClick={()=>set({expires:addDays(todayJST(),30)})}>30日後</button></span></>}</fieldset>
  <label className="talkFile"><Paperclip size={22}/><span>ファイルを付ける（任意）</span><input type="file" name="file" multiple accept={boardAccept}/><small>PDF・Word・Excel・画像・テキスト ／ 5つまで・1つ20 MBまで<br/>PDF・画像は一覧に小さなプレビューが出ます</small></label>
  <label className="boardCheckbox"><input type="checkbox" checked={draft.important} onChange={e=>set({important:e.target.checked})}/><Star size={15}/>重要なお知らせにする</label>
  <label className="boardCheckbox pin"><input type="checkbox" checked={draft.pinned} onChange={e=>set({pinned:e.target.checked})}/><Pin size={15}/>一覧の一番上にピン留めする</label>
  <div className="talkSelected">書いた人：{myName} さん</div>
  <button className="talkPrimary" disabled={busy}><Send size={16}/>{busy?'送っています…':'回覧板に載せる'}</button>
  {!saving?<button type="button" className="talkSecondary" disabled={busy||!draft.title.trim()} onClick={()=>{setTemplateName(draft.title.trim().slice(0,boardLimits.name));setSaving(true)}}><BookmarkPlus size={15}/>この内容をテンプレートに保存</button>
  :<div className="boardTemplateSave"><input aria-label="テンプレート名" maxLength={boardLimits.name} value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="テンプレート名"/><button type="button" className="talkSecondary" disabled={busy||!templateName.trim()} onClick={()=>{onSaveTemplate(templateName.trim());setSaving(false)}}>保存する</button><button type="button" className="talkSecondary" onClick={()=>setSaving(false)}>やめる</button></div>}
 </form>;
}
export function VersionForm({title,busy,onSubmit,onCancel,setError}:{title:string;busy:boolean;onSubmit:(form:FormData,files:File[])=>void;onCancel:()=>void;setError:(e:string)=>void}){
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const files=form.getAll('file').filter((x):x is File=>x instanceof File&&x.size>0);const problem=checkFiles(files)||(!files.length?'追加するファイルを選んでください。':'');if(problem){setError(problem);return}onSubmit(form,files)}
 return <form onSubmit={submit} className="talkInput boardWrite"><div className="talkSelected">「{title}」に新しい版を追加します。前の版もそのまま残り、いつでも見られます。</div><label className="talkFile"><Paperclip size={22}/><span>新しい版のファイルを選ぶ</span><input type="file" name="file" multiple required accept={boardAccept}/><small>5つまで・1つ20 MBまで</small></label><label>ひとこと（任意）<input name="note" maxLength={boardLimits.note} placeholder="例：15日の担当を修正しました"/></label><p className="boardHelp">追加すると、全員の「見ました」がもう一度必要になります（前の版の確認記録は残ります）。</p><button className="talkPrimary" disabled={busy}>{busy?'追加しています…':'新しい版として追加する'}</button><button type="button" className="talkSecondary" disabled={busy} onClick={onCancel}>やめる</button></form>;
}
